export const recipes = [
  {
    id: 1,
    img: "https://zafaranic.com/wp-content/uploads/2019/03/%D8%B7%D8%B1%D8%B2-%D8%AA%D9%87%DB%8C%D9%87-%DA%A9%D8%A8%D8%A7%D8%A8-%DA%A9%D9%88%D8%A8%DB%8C%D8%AF%D9%87-%D8%B2%D8%B9%D9%81%D8%B1%D8%A7%D9%86%DB%8C-1.jpg",
    foodName: "کباب کوبیده",
    kitchenName: "شاندیز",
    servings: 4,
    benefits: ["مقدار کمی از چربی", "خوشمزه و سالم"],
    link: "https://zafaranic.com/%DA%A9%D8%A8%D8%A7%D8%A8-%DA%A9%D9%88%D8%A8%DB%8C%D8%AF%D9%87-%D8%B2%D8%B9%D9%81%D8%B1%D8%A7%D9%86%DB%8C/",
  },
  {
    id: 2,
    img: "https://blog.okcs.com/wp-content/uploads/2023/12/45-1.jpg",
    foodName: "فسنجان",
    kitchenName: "رستوران مسلم",
    servings: 4,
    benefits: ["منبع زیاد از ویتامین C", "خوشمزه و سالم"],
    link: "https://blog.okcs.com/fesenjan-ba-gooosht/",
  },
  {
    id: 3,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYePFWZ-9z5qt32H1h328wbCusN1jq7eCC8g&s",
    foodName: "هویج پلو با مرغ",
    kitchenName: "نایب",
    servings: 4,
    benefits: ["منبع زیاد از ویتامین A", "خوشمزه و سالم"],
    link: "https://chishi.ir/8568-havij-polo-morgh-teke/",
  },
  {
    id: 4,
    img: "https://mamifood.org/images/files/%D9%82%D8%A8%D8%A7%D8%AF%DB%8C%204/r20200313090210-min.jpg",
    foodName: "کشک بادمجان",
    kitchenName: "رستوران شهرزاد",
    servings: 4,
    benefits: ["منبع زیاد از آهن", "خوشمزه و سالم"],
    link: "https://mamifood.org/cooking-training/recipe/13909/%D8%B7%D8%B1%D8%B2-%D8%AA%D9%87%DB%8C%D9%87-%DA%A9%D8%B4%DA%A9-%D8%A8%D8%A7%D8%AF%D9%85%D8%AC%D8%A7%D9%86",
  },
  {
    id: 5,
    img: "https://kharidberenj.ir/uploads/f9f7cd511bed4c7c8ed51f30ea3970ab.jpg",
    foodName: "ته‌دیگ",
    kitchenName: "رستوران خونه",
    servings: 4,
    benefits: ["منبع زیاد از کربوهیدرات", "خوشمزه و سالم"],
    link: "https://kharidberenj.ir/blog/How-to-prepare/P45339-tahdig.html",
  },
  {
    id: 6,
    img: "https://narijeh.com/wp-content/uploads/2024/07/%D8%B7%D8%B1%D8%B2-%D8%AA%D9%87%DB%8C%D9%87-%DA%A9%D9%88%DA%A9%D9%88-%D8%B3%D8%A8%D8%B2%DB%8C.jpg",
    foodName: "کوکو سبزی",
    kitchenName: "رستوران طهران قدیم",
    servings: 4,
    benefits: ["منبع زیاد از ویتامین K", "خوشمزه و سالم"],
    link: "https://narijeh.com/%D8%B7%D8%B1%D8%B2-%D8%AA%D9%87%DB%8C%D9%87-%DA%A9%D9%88%DA%A9%D9%88%D8%B3%D8%A8%D8%B2%DB%8C/",
  },
  {
    id: 7,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMuDNfmdCz6qFRS5ZTUco12YoM7A8uzHE-mA&s",
    foodName: "آبگوشت",
    kitchenName: "رستوران آرکیدا",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://kermany.com/dietitian-broth/",
  },
  {
    id: 8,
    img: "https://setare.com/files/1398/06/04/%D8%AA%D8%B1%DA%A9%DB%8C%D8%A8-%D8%B3%D8%A8%D8%B2%DB%8C-%D8%B3%D8%A8%D8%B2%DB%8C-%D9%BE%D9%84%D9%88.jpg",
    foodName: "سبزی پلو",
    kitchenName: "رستوران ایرانی",
    servings: 4,
    benefits: ["منبع زیاد از ویتامین C", "خوشمزه و سالم"],
    link: "https://setare.com/fa/news/34015/%D8%B3%D8%A8%D8%B2%DB%8C-%D8%B3%D8%A8%D8%B2%DB%8C-%D9%BE%D9%84%D9%88-%D8%B4%D8%A7%D9%85%D9%84-%DA%86%D9%87-%D8%B3%D8%A8%D8%B2%DB%8C-%D9%87%D8%A7%DB%8C%DB%8C-%D8%A7%D8%B3%D8%AA/",
  },
  {
    id: 9,
    img: "https://cdn.fararu.com/files/fa/news/1403/2/17/2024604_606.jpg",
    foodName: "ماست و خیار",
    kitchenName: "رستوران شاطر عباس",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://fararu.com/fa/news/732556/%D8%B7%D8%B1%D8%B2-%D8%AA%D9%87%DB%8C%D9%87-%D9%85%D8%A7%D8%B3%D8%AA-%D9%88-%D8%AE%DB%8C%D8%A7%D8%B1-%D9%88%DB%8C%DA%98%D9%87-%D8%AE%D9%88%D8%B4%D9%85%D8%B2%D9%87%E2%80%8C%D8%AA%D8%B1%DB%8C%D9%86-%D9%85%D8%A7%D8%B3%D8%AA-%D9%88-%D8%AE%DB%8C%D8%A7%D8%B1-%D8%B9%D9%85%D8%B1%D8%AA%D8%A7%D9%86",
  },
  {
    id: 10,
    img: "https://chishi.ir/wp-content/uploads/2020/06/baghali-polo-ba-mahiche.jpg",
    foodName: "باقالی پلو",
    kitchenName: "رستوران باغچه",
    servings: 4,
    benefits: ["منبع زیاد از آهن", "خوشمزه و سالم"],
    link: "https://chishi.ir/2905-baghali-polo-ba-mahiche/",
  },
  {
    id: 11,
    img: "https://chishi.ir/wp-content/uploads/2022/03/khoresh-gheyme-200-nafar.jpg",
    foodName: "قیمه",
    kitchenName: "رستوران شاطر عباس",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://chishi.ir/27378-khoresh-gheyme-200-nafar/",
  },
  {
    id: 12,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjpxcxPex0qvACqazU491Ds2CXsTGUbXLJVA&s",
    foodName: "قرمه سبزی",
    kitchenName: "رستوران باغچه",
    servings: 4,
    benefits: ["منبع زیاد از آهن", "خوشمزه و سالم"],
    link: "https://blog.okcs.com/khoresh-ghormeh-sabzi-recipe/",
  },
  {
    id: 13,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGq0fzOnC_1tz0IeGaCoc0JuMtkb4i5weCwQ&s",
    foodName: "زرشک پلو با مرغ",
    kitchenName: "رستوران مسلم",
    servings: 4,
    benefits: ["منبع زیاد از ویتامین C", "خوشمزه و سالم"],
    link: "https://ajiledalat.com/blog/%D8%B7%D8%B1%D8%B2-%D8%AA%D9%87%DB%8C%D9%87-%D8%B2%D8%B1%D8%B4%DA%A9-%D9%BE%D9%84%D9%88-%D8%A8%D8%A7-%D9%85%D8%B1%D8%BA/",
  },
  {
    id: 14,
    img: "https://www.alamto.com/wp-content/uploads/2022/03/1399020910160430020245954.jpg",
    foodName: "آش رشته",
    kitchenName: "رستوران نایب",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://www.alamto.com/cooking/homemade-noodle-ash-recipe",
  },
  {
    id: 15,
    img: "https://parsiday.com/wp-content/uploads/2018/11/okra-stew.jpg",
    foodName: "خورش بامیه",
    kitchenName: "رستوران شهرزاد",
    servings: 4,
    benefits: ["منبع زیاد از ویتامین C", "خوشمزه و سالم"],
    link: "https://parsiday.com/193-okra-stew/",
  },
  {
    id: 16,
    img: "https://panamag.ir/wp-content/uploads/2021/09/loobia-polo.jpg",
    foodName: "لوبیا پلو",
    kitchenName: "رستوران طهران قدیم",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://panamag.ir/307-loobia-polo/",
  },
  {
    id: 17,
    img: "https://sarashpazpapion.com/content/files/recipes/pictures/web/2016/10/8/tfbbsd9kbdelop5vbti93djd5uglfq8uBN5ZBZu0yZJefkqA.webp",
    foodName: "مرغ سوخاری",
    kitchenName: "رستوران آرکیدا",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://sarashpazpapion.com/recipe/1147/%D9%85%D8%B1%D8%BA-%D8%B3%D9%88%D8%AE%D8%A7%D8%B1%DB%8C",
  },
  {
    id: 18,
    img: "https://salamdonya.com/assets/images/37/3762c3dh9.jpg",
    foodName: "آش ماست",
    kitchenName: "رستوران ایرانی",
    servings: 4,
    benefits: ["منبع زیاد از کلسیم", "خوشمزه و سالم"],
    link: "https://salamdonya.com/recipe/yogurt-soup-ashe-mast-shirazi-recipe",
  },
  {
    id: 22,
    img: "",
    foodName: "میرزا قاسمی",
    kitchenName: "رستوران نایب",
    servings: 4,
    benefits: ["منبع زیاد از ویتامین C", "خوشمزه و سالم"],
    link: "",
  },
  {
    id: 23,
    img: "https://kermany.com/wp-content/uploads/2021/05/1-3.jpg",
    foodName: "پلو با ماهی",
    kitchenName: "رستوران شاندیز",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://kermany.com/dietitian-mirza-qasemi/",
  },
  {
    id: 24,
    img: "https://blog.okala.com/wp-content/uploads/2024/02/Tahchin-Meat-and-carrot.jpg",
    foodName: "ته‌چین مرغ",
    kitchenName: "رستوران طهران",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://blog.okala.com/tahchine-majlesi/",
  },
  {
    id: 25,
    img: "https://kalleh.com/book/wp-content/uploads/sites/2/2023/10/dolmeh-tabrizi.jpg.webp",
    foodName: "دلمه برگ مو",
    kitchenName: "رستوران مسلم",
    servings: 4,
    benefits: ["منبع زیاد از ویتامین C", "خوشمزه و سالم"],
    link: "https://kalleh.com/book/recipe/%D8%B7%D8%B1%D8%B2-%D8%AA%D9%87%DB%8C%D9%87-%D8%AF%D9%84%D9%85%D9%87-%D8%A8%D8%B1%DA%AF-%D9%85%D9%88-%D8%AA%D8%A8%D8%B1%DB%8C%D8%B2%DB%8C/",
  },
  {
    id: 26,
    img: "https://sarashpazpapion.com/content/files/recipes/pictures/web/2016/10/8/tnj8pfsa454fkae61igoguhmj1o23jm0DiGNATefb3mxr12t.webp",
    foodName: "کباب بختیاری",
    kitchenName: "رستوران شهرزاد",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://sarashpazpapion.com/recipe/219/%DA%A9%D8%A8%D8%A7%D8%A8-%D8%A8%D8%AE%D8%AA%DB%8C%D8%A7%D8%B1%DB%8C",
  },
  {
    id: 27,
    img: "https://noktechi.ir/wp-content/uploads/2021/07/khoresh-aloo-esfenaj.jpg",
    foodName: "خورش آلو اسفناج",
    kitchenName: "رستوران شاطر عباس",
    servings: 4,
    benefits: ["منبع زیاد از ویتامین C", "خوشمزه و سالم"],
    link: "https://noktechi.ir/833-khoresh-aloo-esfenaj/",
  },
  {
    id: 28,
    img: "https://chishi.ir/wp-content/uploads/2021/09/kookoo-sibzamini-havij.jpg",
    foodName: "کوکو سیب زمینی",
    kitchenName: "رستوران طهران قدیم",
    servings: 4,
    benefits: ["منبع زیاد از کربوهیدرات", "خوشمزه و سالم"],
    link: "https://chishi.ir/21688-kookoo-sibzamini-havij/",
  },
  {
    id: 29,
    img: "https://media.hamshahrionline.ir/d/2021/01/01/4/4533564.jpg",
    foodName: "آش ترخینه",
    kitchenName: "رستوران آرکیدا",
    servings: 4,
    benefits: ["منبع زیاد از فیبر", "خوشمزه و سالم"],
    link: "https://www.hamshahrionline.ir/news/577033/%D8%B7%D8%B1%D8%B2-%D8%AA%D9%87%DB%8C%D9%87-%D8%A2%D8%B4-%D8%AA%D8%B1%D8%AE%DB%8C%D9%86%D9%87-%D8%A8%D9%87-%D8%B3%D8%A7%D8%AF%D9%87-%D8%AA%D8%B1%DB%8C%D9%86-%D8%B1%D9%88%D8%B4-%D8%BA%D8%B0%D8%A7%DB%8C%DB%8C-%D9%85%D9%81%DB%8C%D8%AF-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%B3%D8%B1%D9%85%D8%A7%D8%AE%D9%88%D8%B1%D8%AF%DA%AF%DB%8C",
  },
  {
    id: 30,
    img: "https://darnahayat.ir/wp-content/uploads/2021/09/morgh-torsh.jpg",
    foodName: "مرغ ترش",
    kitchenName: "رستوران ایرانی",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://darnahayat.ir/203-morgh-torsh/",
  },
  {
    id: 31,
    img: "",
    foodName: "باقالا قاتق",
    kitchenName: "رستوران مسلم",
    servings: 4,
    benefits: ["منبع زیاد از فیبر", "خوشمزه و سالم"],
    link: "",
  },
  {
    id: 32,
    img: "https://chishi.ir/wp-content/uploads/2020/07/baghela-ghatogh.jpg",
    foodName: "آش دوغ",
    kitchenName: "رستوران شاندیز",
    servings: 4,
    benefits: ["منبع زیاد از کلسیم", "خوشمزه و سالم"],
    link: "https://chishi.ir/3516-baghela-ghatogh/",
  },
  {
    id: 33,
    img: "https://mschef.ir/wp-content/uploads/2020/12/khoresht-karafs-mschef-09.jpg",
    foodName: "خورش کرفس",
    kitchenName: "رستوران نایب",
    servings: 4,
    benefits: ["منبع زیاد از فیبر", "خوشمزه و سالم"],
    link: "https://mschef.ir/%D8%B7%D8%B1%D8%B2-%D8%AA%D9%87%DB%8C%D9%87-%D8%AE%D9%88%D8%B1%D8%B4%D8%AA-%DA%A9%D8%B1%D9%81%D8%B3-%D9%85%D8%AC%D9%84%D8%B3%DB%8C-%D9%88-%D8%AC%D8%A7-%D8%A7%D9%81%D8%AA%D8%A7%D8%AF%D9%87/",
  },
  {
    id: 34,
    img: "https://darnahayat.ir/wp-content/uploads/2023/12/mahi-sorkh-shodeh.jpg",
    foodName: "ماهی سرخ کرده",
    kitchenName: "رستوران شهرزاد",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://darnahayat.ir/9098-mahi-sorkh-shode/",
  },
  {
    id: 36,
    img: "https://chishi.ir/wp-content/uploads/2020/08/kabab-torsh.jpg",
    foodName: "کباب ترش",
    kitchenName: "رستوران مسلم",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://chishi.ir/4185-kabab-torsh/",
  },
  {
    id: 37,
    img: "https://www.ghafaridiet.com/upload/article/1706894278.jpg",
    foodName: "آش شله قلمکار",
    kitchenName: "رستوران شاندیز",
    servings: 4,
    benefits: ["منبع زیاد از کربوهیدرات", "خوشمزه و سالم"],
    link: "https://www.ghafaridiet.com/article/%D8%A2%D8%B4-%D8%B4%D9%84%D9%87-%D9%82%D9%84%D9%85%DA%A9%D8%A7%D8%B1",
  },
  {
    id: 40,
    img: "https://noktechi.ir/wp-content/uploads/2021/07/koufte-tabrizi.jpg",
    foodName: "کوفته تبریزی",
    kitchenName: "رستوران طهران قدیم",
    servings: 4,
    benefits: ["منبع زیاد از پروتئین", "خوشمزه و سالم"],
    link: "https://noktechi.ir/850-koufte-tabrizi/",
  },
];
